# Generated by Django 2.2.16 on 2020-11-12 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_user_model_extend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 13, 22, 4, 648043, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
