# Generated by Django 2.2.16 on 2020-11-22 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20201120_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 9, 31, 22, 831126, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
