# Generated by Django 2.2.16 on 2020-11-22 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_auto_20201122_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 12, 58, 13, 310817, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
