# Generated by Django 2.2.16 on 2020-11-24 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0015_auto_20201124_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 13, 59, 39, 395798, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
