# Generated by Django 2.2.16 on 2020-11-24 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0016_auto_20201124_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 14, 8, 59, 719823, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
